camih1338 1 commit rama fix-typo, se limpia el archivo para empezar a…
CamiloHamon13/First_Repository pull request #1
Opened 2021-06-09 01:42 UTC by CamiloHamon13

… estructurar de nuevo el proyecto

2021-06-09 01:54 UTC, CamiloHamon-95 requested changes
Hola camih1338, queda pendiente agregar una linea mas a los archivos del controlador especificando el commit

2021-06-09 02:14 UTC, GengisKan-95 approved these changes
Hi guys!

Corregi el problema con el archivo de vista :D

2021-06-12 01:20 UTC, CamiloHamon13 reviewed
Se agregó una nueva línea a los archivos de Controlador de la rama fix-typo

2021-06-12 02:46 UTC, CamiloHamon-95 approved these changes
Perfecto camih1338, gracias

2021-06-12 02:53 UTC, merged